//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLauncher.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeLauncher.Translations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О ЛАУНЧЕРЕ.
        /// </summary>
        internal static string AboutTabText {
            get {
                return ResourceManager.GetString("AboutTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие после запуска:.
        /// </summary>
        internal static string ActionAfterLaunch {
            get {
                return ResourceManager.GetString("ActionAfterLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление профиля.
        /// </summary>
        internal static string AddingProfileTitle {
            get {
                return ResourceManager.GetString("AddingProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление нового пользователя.
        /// </summary>
        internal static string AddNewUserBox {
            get {
                return ResourceManager.GetString("AddNewUserBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить нового пользователя.
        /// </summary>
        internal static string AddNewUserButton {
            get {
                return ResourceManager.GetString("AddNewUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить профиль.
        /// </summary>
        internal static string AddProfileButtonText {
            get {
                return ResourceManager.GetString("AddProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать старые &quot;Alpha&quot; сборки(от 2010).
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dedepete.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоподключение:.
        /// </summary>
        internal static string Autoconnect {
            get {
                return ResourceManager.GetString("Autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать старые &quot;Beta&quot; сборки(2010-2011).
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется проверка библиотек.
        /// </summary>
        internal static string CheckingLibraries {
            get {
                return ResourceManager.GetString("CheckingLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется проверка доступности версии &apos;{0}&apos;.
        /// </summary>
        internal static string CheckingVersionAvailability {
            get {
                return ResourceManager.GetString("CheckingVersionAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрывать вкладку, если завершение было вызвано
        ///принудительно или прошло без ошибок.
        /// </summary>
        internal static string CloseGameOutputText {
            get {
                return ResourceManager.GetString("CloseGameOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОНСОЛЬ.
        /// </summary>
        internal static string ConsoleTabText {
            get {
                return ResourceManager.GetString("ConsoleTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;SESMC&quot; расшифровывается как Space Earth Studio Minecraft. Все права защищены святой водой.
        ///&quot;Minecraft&quot; является торговой маркой Mojang AB. Все права защищены.
        ///Mojang AB является дочерней студией Microsoft Studios..
        /// </summary>
        internal static string CopyrightInfo {
            get {
                return ResourceManager.GetString("CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить версию {0}?.
        /// </summary>
        internal static string DeleteConfirmationText {
            get {
                return ResourceManager.GetString("DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение удаления.
        /// </summary>
        internal static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить версию.
        /// </summary>
        internal static string DeleteVersion {
            get {
                return ResourceManager.GetString("DeleteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработано dedepete из Space Earth Studio Minecraft
        ///Издано Space Earth Studio.
        /// </summary>
        internal static string DevInfo {
            get {
                return ResourceManager.GetString("DevInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        internal static string EditingProfileTitle {
            get {
                return ResourceManager.GetString("EditingProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить профиль.
        /// </summary>
        internal static string EditProfileButtonText {
            get {
                return ResourceManager.GetString("EditProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выводить лог игры в консоль.
        /// </summary>
        internal static string EnableMinecraftLoggingText {
            get {
                return ResourceManager.GetString("EnableMinecraftLoggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать уведомления о наличии новых версий Minecraft.
        /// </summary>
        internal static string EnableMinecraftUpdateAlertsText {
            get {
                return ResourceManager.GetString("EnableMinecraftUpdateAlertsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЫВОД ИГРЫ.
        /// </summary>
        internal static string GameOutput {
            get {
                return ResourceManager.GetString("GameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большое спасибо администрации портала ru-minecraft.ru за содействие в развитии проекта!.
        /// </summary>
        internal static string GratitudesDescription {
            get {
                return ResourceManager.GetString("GratitudesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодарности.
        /// </summary>
        internal static string GratitudesText {
            get {
                return ResourceManager.GetString("GratitudesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин и/или пароль введены неверно!.
        /// </summary>
        internal static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Независимая.
        /// </summary>
        internal static string Independent {
            get {
                return ResourceManager.GetString("Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить путь до Java! Пожалуйста, укажите путь к исполняемому файлу вручную..
        /// </summary>
        internal static string JavaDetectionFailed {
            get {
                return ResourceManager.GetString("JavaDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполняемый файл:.
        /// </summary>
        internal static string JavaExecutable {
            get {
                return ResourceManager.GetString("JavaExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Флаги JVM:.
        /// </summary>
        internal static string JavaFlags {
            get {
                return ResourceManager.GetString("JavaFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убить процесс.
        /// </summary>
        internal static string KillProcess {
            get {
                return ResourceManager.GetString("KillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        internal static string LanguageTag {
            get {
                return ResourceManager.GetString("LanguageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск игры.
        /// </summary>
        internal static string LaunchButtonText {
            get {
                return ResourceManager.GetString("LaunchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас лицензионный аккаунт?.
        /// </summary>
        internal static string LicenseQuestion {
            get {
                return ResourceManager.GetString("LicenseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛИЦЕНЗИИ.
        /// </summary>
        internal static string LicensesTabText {
            get {
                return ResourceManager.GetString("LicensesTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УПРАВЛЕНИЕ ВЕРСИЯМИ.
        /// </summary>
        internal static string ManageVersionsTabText {
            get {
                return ResourceManager.GetString("ManageVersionsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCoffline - лучшая программа для серверных администраторов!.
        /// </summary>
        internal static string MCofflineDescription {
            get {
                return ResourceManager.GetString("MCofflineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОВОСТИ.
        /// </summary>
        internal static string NewsTabText {
            get {
                return ResourceManager.GetString("NewsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник/Логин:.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть раб. директорию.
        /// </summary>
        internal static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть расположение.
        /// </summary>
        internal static string OpenLocation {
            get {
                return ResourceManager.GetString("OpenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать сторонние версии(Forge, LiteLoader, etc.).
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнёры.
        /// </summary>
        internal static string PartnersText {
            get {
                return ResourceManager.GetString("PartnersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный профиль уже существует в списке!.
        /// </summary>
        internal static string ProfileAlreadyExistsErrorText {
            get {
                return ResourceManager.GetString("ProfileAlreadyExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить профиль &apos;{0}&apos;?.
        /// </summary>
        internal static string ProfileDeleteConfirmationText {
            get {
                return ResourceManager.GetString("ProfileDeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название профиля:.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов к загрузке версии {0}.
        /// </summary>
        internal static string ReadyToDownload {
            get {
                return ResourceManager.GetString("ReadyToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов к запуску версии {0}.
        /// </summary>
        internal static string ReadyToLaunch {
            get {
                return ResourceManager.GetString("ReadyToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранного пользователя.
        /// </summary>
        internal static string RemoveSelectedUser {
            get {
                return ResourceManager.GetString("RemoveSelectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАСТРОЙКИ.
        /// </summary>
        internal static string SettingsTabText {
            get {
                return ResourceManager.GetString("SettingsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать экспериментальные сборки (&quot;snapshots&quot;).
        /// </summary>
        internal static string Snapshots {
            get {
                return ResourceManager.GetString("Snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать префикс [GAME] для логов Minecraft.
        /// </summary>
        internal static string UseGamePrefixText {
            get {
                return ResourceManager.GetString("UseGamePrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать последнюю версию.
        /// </summary>
        internal static string UseLatestVersion {
            get {
                return ResourceManager.GetString("UseLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение окна:.
        /// </summary>
        internal static string WindowResolution {
            get {
                return ResourceManager.GetString("WindowResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочая директория:.
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
    }
}
